# Generated by Django 4.2.3 on 2023-12-19 11:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0006_alter_file_expires_at_transcriptsandsummaries'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transcriptsandsummaries',
            old_name='uploaded_at',
            new_name='uploaded_on',
        ),
        migrations.AlterField(
            model_name='file',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 12, 19, 11, 47, 36, 862277, tzinfo=datetime.timezone.utc)),
        ),
    ]
