# Generated by Django 4.2.3 on 2023-12-19 11:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0007_rename_uploaded_at_transcriptsandsummaries_uploaded_on_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 12, 19, 11, 48, 0, 487185, tzinfo=datetime.timezone.utc)),
        ),
    ]
