# Generated by Django 4.2.3 on 2024-01-01 09:26

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0009_alter_file_expires_at_userdevicedata'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userdevicedata',
            old_name='uploaded_on',
            new_name='updated_on',
        ),
        migrations.AddField(
            model_name='userdevicedata',
            name='user',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='file',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 1, 1, 9, 30, 15, 296091, tzinfo=datetime.timezone.utc)),
        ),
    ]
