# Generated by Django 4.2.9 on 2024-01-17 17:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0010_rename_uploaded_on_userdevicedata_updated_on_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 1, 17, 17, 15, 48, 428898, tzinfo=datetime.timezone.utc)),
        ),
    ]
