# Generated by Django 4.2.9 on 2024-01-17 17:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0011_alter_file_expires_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 1, 17, 17, 16, 19, 172563, tzinfo=datetime.timezone.utc)),
        ),
    ]
